### ISSUE TITLE
Errors running the script

### ISSUE THREAD

**Issue by austinbarberrepo** [an00byss/CiscoRDP#1]
I'm running this on a Hyper-V machine. Here are the errors that I am getting:

> Get-Process : Cannot find a process with the name "vpnagent". Verify the process name and call the cmdlet again.
At C:\temp\ciscoRDP.ps1:7 char:18
+ $ciscovpnagent = Get-Process vpnagent
    + CategoryInfo          : ObjectNotFound: (vpnagent:String) [Get-Process], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.GetProcessCommand

> Get-NetIPInterface : No MSFT_NetIPInterface objects found with property 'InterfaceAlias' equal to 'Ethernet 2'.
Verify the value of the property and retry.
At C:\temp\ciscoRDP.ps1:32 char:9
+         Get-NetIPInterface -InterfaceAlias "Ethernet 2" -Verbose | Fo 
    + CategoryInfo          : ObjectNotFound: (Ethernet 2:String) [Get-NetIPInterface], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_InterfaceAlias,Get-NetIPInterface

I've modified your script with my vpn connect to URL and my computer hostname. I've ran it a couple of times and I get the same thing. Could you maybe take a look and help me out please?

**Comment by an00byss** [comment]
Looks like the vpnagent isn't running or cannot be found on your system. If for some reason it is running try specifying the path for the executable.
